<a href="https://colab.research.google.com/github/Rishabh-Thapliyal/Google-colab/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from keras.callbacks import EarlyStopping
from keras.layers import Dropout

In [ ]:
# Load the IMDb dataset
num_words = 10000  # Number of most frequent words to keep
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=num_words)

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
# Row with words is changed to sequence of numbers. Every word gets a number based on its frequency in the document

In [ ]:
x_train[0][:10]

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65]

In [ ]:
# evry row will have different length for sequence of numbers

len(x_train[0]), len(x_train[1])

(218, 189)

In [ ]:
# Pad sequences to have the same length
max_length = 200  # Maximum sequence length
x_train = pad_sequences(x_train, maxlen=max_length, padding='pre')
x_test = pad_sequences(x_test, maxlen=max_length, padding='pre')

In [ ]:
len(x_train[0]), len(x_train[1])

(200, 200)

In [ ]:
input_1d = x_train[0]
input_2d = np.array([x_train[0], x_train[1]])
input_2d

array([[   5,   25,  100,   43,  838,  112,   50,  670,    2,    9,   35,
         480,  284,    5,  150,    4,  172,  112,  167,    2,  336,  385,
          39,    4,  172, 4536, 1111,   17,  546,   38,   13,  447,    4,
         192,   50,   16,    6,  147, 2025,   19,   14,   22,    4, 1920,
        4613,  469,    4,   22,   71,   87,   12,   16,   43,  530,   38,
          76,   15,   13, 1247,    4,   22,   17,  515,   17,   12,   16,
         626,   18,    2,    5,   62,  386,   12,    8,  316,    8,  106,
           5,    4, 2223, 5244,   16,  480,   66, 3785,   33,    4,  130,
          12,   16,   38,  619,    5,   25,  124,   51,   36,  135,   48,
          25, 1415,   33,    6,   22,   12,  215,   28,   77,   52,    5,
          14,  407,   16,   82,    2,    8,    4,  107,  117, 5952,   15,
         256,    4,    2,    7, 3766,    5,  723,   36,   71,   43,  530,
         476,   26,  400,  317,   46,    7,    4,    2, 1029,   13,  104,
          88,    4,  381,   15,  297, 

In [ ]:
embedding_layer = tf.keras.layers.Embedding(num_words, 5)

In [ ]:
# input to embedding layer can be 1d as well as 2d
embedding_output = embedding_layer(input_1d)
embedding_output

<tf.Tensor: shape=(200, 5), dtype=float32, numpy=
array([[ 0.01919227, -0.01216179, -0.03128538,  0.04186553, -0.03310065],
       [ 0.01139163, -0.00569863, -0.00158126,  0.03826315,  0.00572319],
       [ 0.03546956,  0.04259116, -0.02048081,  0.02053437, -0.04959307],
       [ 0.0225465 ,  0.04854618, -0.04669328, -0.03731062, -0.0370839 ],
       [-0.00162822,  0.04283604,  0.02965018,  0.01653839,  0.0241874 ],
       [-0.04328128,  0.02445361,  0.01194006,  0.0031513 ,  0.047814  ],
       [ 0.0178764 ,  0.04338571, -0.03584503, -0.03507216, -0.01982794],
       [ 0.03401503,  0.02850537, -0.00632366, -0.02631893, -0.01083481],
       [-0.03705746, -0.01173189, -0.02252402, -0.03457221,  0.01223124],
       [ 0.02312664, -0.04504855, -0.00127838, -0.02896926,  0.04385031],
       [-0.03231008,  0.010206  ,  0.00751461, -0.04676848,  0.01540676],
       [-0.02293896,  0.01788593, -0.04216766, -0.00218041, -0.03445733],
       [ 0.03747329, -0.02246103, -0.03090761,  0.00455778, -0

In [ ]:
# Confirming- for same words, the embedding vector will be the same
embedding_layer(np.array([2,2]))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-0.03705746, -0.01173189, -0.02252402, -0.03457221,  0.01223124],
       [-0.03705746, -0.01173189, -0.02252402, -0.03457221,  0.01223124]],
      dtype=float32)>

In [ ]:
lstm = tf.keras.layers.LSTM(4)

In [ ]:
embedding_output.shape

TensorShape([200, 5])

In [ ]:
# LSTM requires the 3 dimensional array as input

lstm_input = tf.reshape(embedding_output, (1,embedding_output.shape[0], embedding_output.shape[1]))
lstm_input

<tf.Tensor: shape=(1, 200, 5), dtype=float32, numpy=
array([[[ 0.01919227, -0.01216179, -0.03128538,  0.04186553,
         -0.03310065],
        [ 0.01139163, -0.00569863, -0.00158126,  0.03826315,
          0.00572319],
        [ 0.03546956,  0.04259116, -0.02048081,  0.02053437,
         -0.04959307],
        [ 0.0225465 ,  0.04854618, -0.04669328, -0.03731062,
         -0.0370839 ],
        [-0.00162822,  0.04283604,  0.02965018,  0.01653839,
          0.0241874 ],
        [-0.04328128,  0.02445361,  0.01194006,  0.0031513 ,
          0.047814  ],
        [ 0.0178764 ,  0.04338571, -0.03584503, -0.03507216,
         -0.01982794],
        [ 0.03401503,  0.02850537, -0.00632366, -0.02631893,
         -0.01083481],
        [-0.03705746, -0.01173189, -0.02252402, -0.03457221,
          0.01223124],
        [ 0.02312664, -0.04504855, -0.00127838, -0.02896926,
          0.04385031],
        [-0.03231008,  0.010206  ,  0.00751461, -0.04676848,
          0.01540676],
        [-0.02293896,  

In [ ]:
# lstm = tf.keras.layers.LSTM(4)
lstm_output = lstm(lstm_input, )
lstm_output

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.00120903, -0.0019355 ,  0.00586454,  0.00911274]],
      dtype=float32)>

In [ ]:
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(lstm_input)
print(whole_seq_output.shape, final_memory_state.shape, final_carry_state.shape)

(1, 200, 4) (1, 4) (1, 4)


In [ ]:
whole_seq_output

<tf.Tensor: shape=(1, 200, 4), dtype=float32, numpy=
array([[[ 7.32314680e-03, -6.20215840e-04,  1.34168845e-03,
         -8.42739083e-03],
        [ 5.43124788e-03,  2.58780085e-03,  6.64755236e-03,
         -1.12658562e-02],
        [ 1.09182633e-02,  6.37611886e-03,  2.16872741e-06,
         -1.93888936e-02],
        [ 1.59394760e-02,  4.49198345e-03, -1.29928812e-02,
         -2.20569335e-02],
        [ 6.33290969e-03,  1.13590835e-02, -8.02970212e-03,
         -2.06743702e-02],
        [-3.08129820e-03,  1.55880768e-02, -9.07590520e-03,
         -1.64654553e-02],
        [ 4.62635327e-03,  1.13139320e-02, -1.92945562e-02,
         -1.64049659e-02],
        [ 7.85157643e-03,  6.88416557e-03, -1.80561375e-02,
         -1.31545365e-02],
        [ 5.40334964e-03,  1.94707199e-03, -2.00878140e-02,
         -7.39770103e-03],
        [ 3.80464364e-03, -6.92652026e-03, -6.35389937e-03,
          3.20208003e-03],
        [-1.19358511e-03, -7.14139128e-03, -1.04965875e-02,
          7.45880

In [ ]:
whole_seq_output[0][199]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.00044488,  0.00302304,  0.00683789,  0.00047781], dtype=float32)>

In [ ]:
# whole seq output last entry will be same as final memory state

final_memory_state

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.00044488,  0.00302304,  0.00683789,  0.00047781]],
      dtype=float32)>

In [ ]:
dense_layer = tf.keras.layers.Dense(1, activation='sigmoid')

In [ ]:
dense_output = dense_layer(final_memory_state)
dense_output

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.49985415]], dtype=float32)>

In [ ]:
tf.reshape(y_train[0], (1,1))

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[1]])>

In [ ]:
loss_ = tf.keras.losses.binary_crossentropy( tf.reshape(y_train[0], (1,1)), dense_output)
loss_

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.693439], dtype=float32)>

In [ ]:
# tf.keras.metrics.Accuracy(name = 'accuracy',tf.reshape(y_train[0], (1,1)), loss_)
acc_metric = tf.keras.metrics.Accuracy(name = 'accuracy')
acc_metric.update_state(tf.reshape(y_train[0], (1,1)), loss_)
acc_metric.result().numpy()

0.0

In [ ]:
# gradients = tf.GradientTape.gradient(loss_, model.trainable_weights)
# optimizer.apply_gradients(zip(gradients, model.trainable_weights))

In [ ]:
model = Sequential()

model.add(Embedding(input_dim=num_words, output_dim=128, input_length=max_length))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3, batch_size=64)

Epoch 1/3
391/391 [==============================] - 259s 655ms/step - loss: 0.4052 - accuracy: 0.8164 - val_loss: 0.3258 - val_accuracy: 0.8656
Epoch 2/3
391/391 [==============================] - 249s 638ms/step - loss: 0.2494 - accuracy: 0.8998 - val_loss: 0.3271 - val_accuracy: 0.8664
Epoch 3/3
391/391 [==============================] - 247s 632ms/step - loss: 0.1769 - accuracy: 0.9341 - val_loss: 0.3472 - val_accuracy: 0.8594


In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")